### PR TITLE
Use local sgdisk in case it is not in PATH

### PR DESCRIPTION
**Pull request by jockebech**
On some systems sgdisk is not on the users default PATH and it does not
seem like this script folder is on the PATH either and therefore we must
use the form "./sgdisk" and not just sgdisk to prevent errors when
building the ptable using the locally stored sgdisk binary.

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>

### CODE REVIEW

**Comment by jockebech** [comment]
Btw, I have a weird issue. On my machine running Debian. If I force the variable to my distros sgdisk, i.e., `/sbin/sgdisk/` then everything works. But if I use the local `sgdisk` binary in the git, then I get this when trying to do a recovery.
```bash
fastboot flash ptable /media/jbech/SSHD_LINUX/devel/optee_projects/hikey/build/../l-loader/ptable-linux-8g.img                               
target reported max download size of 268435456 bytes                        
sending 'ptable' (17 KB)...                                                                                                                  OKAY [  0.001s]                                                                                                   
writing 'ptable'...                                                           
OKAY [  0.003s]                                                                                                                              finished. total time: 0.004s                                                                                                                 
fastboot flash fastboot /media/jbech/SSHD_LINUX/devel/optee_projects/hikey/build/../arm-trusted-firmware/build/hikey/release/fip.bin
target reported max download size of 268435456 bytes                                                                                         
sending 'fastboot' (1418 KB)...                                                                                                              
FAILED (remote: invalid partition)
...
```
Here comes the funny part:
```bash
jbech@debby ~ 
$ sudo /sbin/sgdisk --version
GPT fdisk (sgdisk) version 1.0.1
```

```bash
jbech@debby /media/jbech/SSHD_LINUX/devel/optee_projects/hikey/l-loader [sgdisk_warning !]
$ ./sgdisk --version                                                                                                                         
GPT fdisk (sgdisk) version 1.0.1
```
I.e., same version, but first one is dynamically linked and the second one is statically linked. I thought it could be good to know about this, since it is pretty hard to track down this issue. I've tried switching between the several times, so I'm pretty sure about it now. I've also diff'ed the output, but that doesn't really reveal anything.

// Joakim

**Comment by vchong** [comment]
Just making a guess here, but is it possible that /media/* is mounted differently, some incompatible format?

**Comment by vchong** [comment]
Or maybe something is off with the local `sgdisk` since according to https://github.com/96boards-hikey/l-loader/commits/testing/hikey960_v1.2/sgdisk it's a hacked(?) version.

**Comment by jockebech** [comment]
@vchong I don't think `/media/*` has anything to do with this. It's a normal ext4 drive. I have no clue what the issue is, but for sure there is something that makes it work and not work depending on which `sgdisk` I'm using. Btw, after being off for the weekend I doubt my fix here is any good. Since, now it will always use the locally shipped (and eventually broken) `sgdisk`. Without my fix it tried to find what was in your `$PATH` instead. It'd probably be better to have something like: 
```bash
SGDISK=`which sgdisk`
```
and if that evaluates to an empty string, then use the local version.

**Comment by hzhuang1** [comment]
It's not preferred to always use the hack sgdisk. Since the hack sgdisk is forced to build partition table with 4KB. In HiKey, we're using eMMC with 512B page size.

**Comment by vchong** [comment]
Is the copy of sgdisk here still a hacked version? There are many scripts and makefiles that still point to this copy. Is it better than to replace it with a proper version?

**Comment by hzhuang1** [comment]
The sgdisk in l-loader repository is a hacked version. We shouldn't copy a normal version of sgdisk into l-loader, since it may make user confusion.

I think user should use the sgdisk in his system. If the tool is not in his default path, just try to run it with sudo.

**Comment by jockebech** [comment]
How can a user tell the difference between this hacked sgdisk and regular sgdisk? That is not mentioned anywhere. Could we add a just a comment somewhere (a README.md?) which lets people know about this?

In any case, my proposed fix here isn't probably what we are looking for, so I'm going to close this PR.

**Comment by hzhuang1** [comment]
Yes, you can add it into README. It's welcome.

**Comment by jockebech** [comment]
Great, I've added this on my own little to-do list. I Will send PR sooner or later for the README.

**Comment by jockebech** [comment]
Old issue, but I had to comment. I've struggled with this for ~2 hours today until I realize that it's the same issue again that I brought up here  ~2 years ago. Debian 10 doesn't have /usr/sbin in the path, so sgdisk wasn't found, but build wise no errors reported. So it's not until you really pay attention to the logfile that you will see this.

**Comment by vchong** [comment]
Please refer to 3rd commit of https://github.com/96boards-hikey/l-loader/pull/32 for asserting existence of sgdisk on PATH.

**Pull request closed without merging**
