### PR TITLE
Misc updts

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Comment by vchong** [comment]
@jbech-linaro fyi sgdisk patch in 3rd commit

**Comment by jockebech** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jockebech** [comment]
You could even add a "Fixes #18" to the commit message if you want to, no strong opinion however.

**Comment by vchong** [comment]
> You could even add a "Fixes #18" to the commit message if you want to, no strong opinion however.

I thought about it, but realized #18 is a PR. Can a PR fix another PR?

**Comment by jockebech** [comment]
> > You could even add a "Fixes #18" to the commit message if you want to, no strong opinion however.
> 
> I thought about it, but realized #18 is a PR. Can a PR fix another PR?

The PR is closed already, I was more thinking about an indication as a reference in the commit message.

**Comment by vchong** [comment]
>>> You could even add a "Fixes #18" to the commit message if you want to, no strong opinion however.

>> I thought about it, but realized #18 is a PR. Can a PR fix another PR?

> The PR is closed already, I was more thinking about an indication as a reference in the commit message.

Ok. Both tag and reference added.

@hzhuang1 @fboudra Please merge if ok. Thanks!

**Pull request merged**
